name: Database Migration
on:
  workflow_call:
    inputs:
      ecr_repository_url:
        type: string
        description: The ECR repository URL to use
        required: true
      image_tag:
        type: string
        description: The image tag to use
        required: true
      ecs_task_definition:
        type: string
        description: The ECS task definition to use
        required: true
      ecs_cluster:
        type: string
        description: The ECS cluster to deploy to
        required: true
      referenced_network_config_ecs_service:
        type: string
        description: The ECS service to reference for the network configuration
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.CICD_AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Get the container name from the task definition
      # Note, modify this if we have more than one container
      - name: Get current task definition from ECS
        id: get-task-definition-container-name
        run: |
          CONTAINER_NAME=$(aws ecs describe-task-definition \
            --task-definition ${{ inputs.ecs_task_definition }} \
            --query taskDefinition.containerDefinitions[0].name \
            --output text)
          echo "CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_OUTPUT

      # Fetch task definition, and render it with the new image replaced
      # This outputs contains the path to the task definition JSON file
      # This does not update the task definition to AWS
      - name: Replace new Image to Task Definition JSON
        id: update-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-family: ${{ inputs.ecs_task_definition }}
          container-name: ${{ steps.get-task-definition-container-name.outputs.CONTAINER_NAME }}
          image: "${{ inputs.ecr_repository_url }}:${{ inputs.image_tag }}"

      # Obtain the network configuration from referenced ECS service.
      - name: Obtain Referenced Service Network Configuration
        id: get-network-config
        run: |
          NETWORK_CONFIG=$(aws ecs describe-services \
            --cluster ${{ inputs.ecs_cluster }} \
            --services ${{ inputs.referenced_network_config_ecs_service }} \
            --output json \
            | jq -r '.services[0].networkConfiguration | @json')
          echo "NETWORK_CONFIG=${NETWORK_CONFIG}" >> $GITHUB_OUTPUT

      # Register Task Definition in AWS
      - name: Register Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        id: register-task-definition
        with:
          task-definition: ${{ steps.update-task-definition.outputs.task-definition }} # Path to the task definition JSON file

      # Run DB migration with the same network configuration
      - name: Run Database Migration Task
        id: run-migration-task
        run: |
          RESP_JSON=$(aws ecs run-task \
            --task-definition ${{ steps.register-task-definition.outputs.task-definition-arn }} \
            --cluster ${{ inputs.ecs_cluster }} \
            --launch-type="FARGATE" \
            --network-configuration '${{ steps.get-network-config.outputs.NETWORK_CONFIG }}' \
            --count 1 \
            --output json)

          echo "$RESP_JSON" | jq -e '.failures | length == 0' >/dev/null || {
            echo "ECS run-task failed:"
            echo "$RESP_JSON" | jq '.failures'
            exit 1
          }

          TASK_ARN=$(echo $RESP_JSON | jq -r '.tasks[0].taskArn')
          echo "TASK_ARN=${TASK_ARN}" >> $GITHUB_OUTPUT

      # Wait for migration task to finish successfully
      - name: Wait for migration task to finish
        run: |
          aws ecs wait tasks-stopped --cluster ${{ inputs.ecs_cluster }} --tasks ${{ steps.run-migration-task.outputs.TASK_ARN }}

          EXIT_CODE=$(aws ecs describe-tasks \
            --cluster ${{ inputs.ecs_cluster }} \
            --tasks ${{ steps.run-migration-task.outputs.TASK_ARN }} \
            --query "tasks[0].containers[0].exitCode" \
            --output text)

          if [ "$EXIT_CODE" -ne 0 ]; then
            exit $EXIT_CODE
          fi

          echo "Migration task finished successfully"
